### ISSUE TITLE
Question about results in Table2 of the main paper?

### ISSUE THREAD

**Issue by gallenszl** [tjqansthd/LapDepth-release#12]
Hello, thank you for your great work! We have two questions about the result reported in Table2 of the main paper. (1) We notice that the released code is evaluated by the the official annotated ground truth. So how can we evaluate the released model with the raw velodyne data? (2) We find that the result reported in Table 2 of the main paper is a littile different with the result reported in readme. Is there any diffence between the two versions? 

Thank you very much!

**Comment by tjqansthd** [comment]
Hi! Thanks for your interest.
(1) KITTI currently provides both the official annotated depth and the raw velodyne depth. So you can download the raw velodyne depth and evaluate the model using the depth data.
(2) The result reported in readme is improved by SyncBatchnorm and a littel fine-tuning.

Thank you!
