### ISSUE TITLE
How to evaluate the depth image for any real-world images?

### ISSUE THREAD

**Issue by angleboy8** [tjqansthd/LapDepth-release#13]
Hi, thank you for sharing your excellent work. Please how to evaluate the depth image for any real-world images. I can try the command line "python eval.py --model_dir ./pretrained/LDRN_KITTI_ResNext101_pretrained_data.pkl --evaluate --batch_size 1 --dataset KITTI --data_path ./datasets/KITTI --gpu_num 0 --img_save". However, it cannot work. If you have some good suggestions, please let me know. I appreciate your help.

**Comment by tjqansthd** [comment]
Hi, thanks for your interest. Sorry for late reply.

The command line ```python eval.py --model_dir ./pretrained/LDRN_KITTI_ResNext101_pretrained_data.pkl --evaluate --batch_size 1 --dataset KITTI --data_path ./datasets/KITTI --gpu_num 0 --img_save``` is for the public dataset KITTI.
If you want to evaluate the model for KITTI dataset, you have to prepare the KITTI dataset following README.md. The dataset should be located in the './datasets/KITTI' path. Or if you want to evaluate the model using other real-world images, the RGB imge and corresponding the ground truth depth map should be prepared. Then you can test the image by directly use the function 'compute_errors' in https://github.com/tjqansthd/LapDepth-release/blob/a9516c40563dc1b45b24e48b3b473e08a7140c41/calculate_error.py#L10-L58

Thank you!
