### ISSUE TITLE
how to train my custom dataset

### ISSUE THREAD

**Issue by xiaopan999** [tjqansthd/LapDepth-release#14]

**Comment by tjqansthd** [comment]
Hi, unfortunately, the current source code in the project only defines a dataloader class for the use of KITTI and NYU dataset. If you want to train your own dataset, you can define a new data loader class for your custom dataset, or modify the data loader class currently defined in './datasets/datasets_list.py' as follows:
https://github.com/tjqansthd/LapDepth-release/blob/a9516c40563dc1b45b24e48b3b473e08a7140c41/datasets/datasets_list.py#L17-L148

Thank you!
