### ISSUE TITLE
How to get the ground truth depth map?

### ISSUE THREAD

**Issue by Pattern6** [tjqansthd/LapDepth-release#15]
Thank you very much for your outstanding work. I am very interested in your work, but I have a doubt about how to get the real depth map mentioned in your paper. The real depth map of Kitti dataset is sparse。

![image](https://user-images.githubusercontent.com/84652468/169486799-7d62db41-793f-4fbd-8306-1a7bb9c70ea2.png)

**Comment by tjqansthd** [comment]
Hi, Thanks for your interest!
As mentioned in README.md, we take an inpainting method from [DenseDepth](https://github.com/ialhashim/DenseDepth) to get dense g.t. Matlab code provided with NYU Depth V2 toolbox is re-implemented to Python code in their repository.
