### ISSUE TITLE
Could not find a version that satisfies the requirement unichr.

### ISSUE THREAD

**Issue by ATTUNE-code** [tjqansthd/LapDepth-release#21]
Hello,
Excuse me, I want to ask why here can't find this function.I find as a result of this function in pyhton3 have been deleted.
But I change into char also cannot use.
How can I solve this problem？Thank you!
![image](https://user-images.githubusercontent.com/70506603/219937110-c6db2a02-f205-47a8-ab85-950dc499e731.png)

**Comment by tjqansthd** [comment]
Hi, you can replace ```scenes = [u''.join(unichr(c) for c in h5_file[obj_ref]) for obj_ref in h5_file['sceneTypes'][0]]``` with
```scenes = [u''.join(chr(c[0]) for c in h5_file[obj_ref]) for obj_ref in h5_file['sceneTypes'][0]]```.
thank you.
