### ISSUE TITLE
OSError: [Errno 22] Invalid argument: Path('checkpoints/sync/04-13-10:14')

### ISSUE THREAD

**Issue by deng29** [tjqansthd/LapDepth-release#3]
hello,
    when I run train.py, the code reaches line 54 “args.save_path.makedirs_p()”，Such an error occurred：OSError: [Errno 22] Invalid argument: Path('checkpoints/sync/04-13-10:14')
    I have been unable to solve this problem......

**Comment by tjqansthd** [comment]
@deng29 Hi,
it seems that '-' or ':' are not recognized in your environment.
you can modify 37 lines in utils.py
```
timestamp = datetime.datetime.now().strftime("%m-%d-%H:%M")
```
to
```
timestamp = datetime.datetime.now().strftime("%m_%d_%H_%M")
```

**Comment by deng29** [comment]
My problem is solved, thank you very much.
