### ISSUE TITLE
Change backbone to ResNet-18

### ISSUE THREAD

**Issue by DavidRecasens** [tjqansthd/LapDepth-release#4]
Hi there! Thanks for sharing this fantastic work :). 

Due to I have a small dataset, the available encoder networks are too large for my purpose. Therefore, I would like to use a smaller ResNet-18 instead. However, I am struggling with the code. This is the code for ResNet-101:

https://github.com/tjqansthd/LapDepth-release/blob/2ea5f29d2e117e765e9da97984bbc5b6de0eddcb/model.py#L338-L383

What would it be like for a ResNet-18?

Cheers!

**Comment by tjqansthd** [comment]
Hi, thanks for your interest!

you can try ResNet-18 to our model, but you need to slightly modify something. For example, the ```dimList``` has to be modified according to the ResNet18 structure. (i.e., [64, 128, 256, 512]). And you have to set ```lv6``` False since ResNet-18 have 4 layers

**Comment by DavidRecasens** [comment]
Hi! Thanks for you reply :)

I tried it but I still have some problems with the tensor sizes. I modified the encoder as you proposed:

`class deepFeatureExtractor_ResNet18(nn.Module):

    def __init__(self, args, lv6=False):
        super(deepFeatureExtractor_ResNet18, self).__init__()
        self.args = args
        # after passing ReLU   : H/2  x W/2
        # after passing Layer1 : H/4  x W/4
        # after passing Layer2 : H/8  x W/8
        self.encoder = models.resnet18(pretrained=True)
        self.fixList = ['layer1.0', 'layer1.1', '.bn']

        del self.encoder.layer4
        del self.encoder.fc
        self.layerList = ['relu', 'layer1', 'layer2', 'layer3']
        self.dimList = [64, 128, 256, 512]

        for name, parameters in self.encoder.named_parameters():
            if name == 'conv1.weight':
                parameters.requires_grad = False
            if any(x in name for x in self.fixList):
                parameters.requires_grad = False

    def forward(self, x):
        out_featList = []
        feature = x
        for k, v in self.encoder._modules.items():
            if k == 'avgpool':
                break
            feature = v(feature)
            # feature = v(features[-1])
            # features.append(feature)
            if any(x in k for x in self.layerList):
                out_featList.append(feature)
        return out_featList

    def freeze_bn(self, enable=False):
        """ Adapted from https://discuss.pytorch.org/t/how-to-train-with-frozen-batchnorm/12106/8 """
        for module in self.modules():
            if isinstance(module, nn.BatchNorm2d):
                module.train() if enable else module.eval()

                module.weight.requires_grad = enable
                module.bias.requires_grad = enable`

And I try the following:
`python train.py --batch_size 8 --dataset synthetic_colon --data_path ./datasets/synthetic_colon --gpu_num 0 --use_dense_depth --encoder ResNet18 --cap 200.0 --max_depth 200.0 --height 256 --width 256 --epochs 50`

Which returns:

> ==> Single GPU Training
=> number of GPU:  0
=> information will be saved in checkpoints/synthetic_colon,50epochs,b8/05-12-11:41
=> Dataset:  synthetic_colon
=> Data height: 256, width: 256 
=> train samples_num: 16016  
=> test  samples_num: 16016  
=> creating model
==> Norm: BN
===============================================
model encoder parameters:  2782784
model decoder parameters:  3898240
Total parameters: 6681024
Total trainable parameters: 6520576
===============================================
=> Model Initialized on GPU: 0 - Single GPU training
training start!
Training for 55 epochs...
  0%|                                                                                                                            | 0/55 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 193, in <module>
    main_worker(args.gpu, ngpus_per_node, args)
  File "train.py", line 162, in main_worker
    loss = train_net(args, Model, optimizer, train_loader,val_loader, args.epochs,logger)
  File "/home/david/GitHub/LapDepth-release/trainer.py", line 194, in train_net
    d_res_list, outputs = model(inputs)
  File "/home/david/anaconda3/envs/LapDepth/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/david/GitHub/LapDepth-release/model.py", line 979, in forward
    d_res_list, depth = self.decoder(out_featList, rgb_list)
  File "/home/david/anaconda3/envs/LapDepth/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/david/GitHub/LapDepth-release/model.py", line 717, in forward
    dense_feat = self.ASPP(dense_feat)                        # Dense feature for lev 5
  File "/home/david/anaconda3/envs/LapDepth/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/david/GitHub/LapDepth-release/model.py", line 545, in forward
    x = self.reduction1(x)
  File "/home/david/anaconda3/envs/LapDepth/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/david/GitHub/LapDepth-release/model.py", line 36, in forward
    return F.conv2d(x, weight, self.bias, self.stride, self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [256, 512, 1, 1], expected input[8, 256, 16, 16] to have 512 channels, but got 256 channels instead

That 8 of [8, 256, 16, 16] is the batch size and my images are 256x256. I have to say I modified the code a little bit to be able to train with my dataset, and I was able to train models with any other encoder. So the problem looks like is still in that new `class deepFeatureExtractor_ResNet18(nn.Module):` I made. Any slight idea which the problem may be?

Greetings!

**Comment by tjqansthd** [comment]
Hi, when I checked the structure of the torchvision's ResNet18 because it is thought that the channel dimension of input features did not fit, there was a slight difference from ResNet101. ResNet18 also has 5 layers ('relu', 'layer1', 'layer2', 'layer3', 'layer4') but the feature is not down-sampled in 'layer1', so the outputs from 'relu' and 'layer1' have same channel and spatial dimension (channel: 64, spatial: H/4 x W/4). Therefore, you can try '''self.layerList = ['layer1', 'layer2', 'layer3', 'layer4']''' and '''self.dimList = [64, 128, 256, 512]'''. Then the channel dimension of features may be fit.

**Comment by DavidRecasens** [comment]
That was the point! Now works perfectly :). Thanks so much for your effort replying. 

I leave the code here in case someone wants to copy and paste:

`class deepFeatureExtractor_ResNet18(nn.Module):`

    def __init__(self, args, lv6=False):
        super(deepFeatureExtractor_ResNet18, self).__init__()
        self.args = args
        # after passing ReLU   : H/2  x W/2
        # after passing Layer1 : H/2  x W/2
        # after passing Layer2 : H/4  x W/4
        # after passing Layer3 : H/8  x W/8
        self.encoder = models.resnet18(pretrained=True)
        self.fixList = ['layer1.0', 'layer1.1', '.bn']

        del self.encoder.layer4
        del self.encoder.fc
        self.layerList = ['relu', 'layer1', 'layer2', 'layer3', 'layer4']
        self.dimList = [64, 64, 128, 256, 512]

        for name, parameters in self.encoder.named_parameters():
            if name == 'conv1.weight':
                parameters.requires_grad = False
            if any(x in name for x in self.fixList):
                parameters.requires_grad = False

    def forward(self, x):
        out_featList = []
        feature = x
        for k, v in self.encoder._modules.items():
            if k == 'avgpool':
                break
            feature = v(feature)
            # feature = v(features[-1])
            # features.append(feature)
            if any(x in k for x in self.layerList):
                out_featList.append(feature)
        return out_featList

    def freeze_bn(self, enable=False):
        """ Adapted from https://discuss.pytorch.org/t/how-to-train-with-frozen-batchnorm/12106/8 """
        for module in self.modules():
            if isinstance(module, nn.BatchNorm2d):
                module.train() if enable else module.eval()

                module.weight.requires_grad = enable
                module.bias.requires_grad = enable
