### ISSUE TITLE
No files to download.

### ISSUE THREAD

**Issue by deng29** [tjqansthd/LapDepth-release#5]
Hello,

when I run "aria2c -x 16 -i ./datasets/kitti_archives_to_download.txt", its appear "No files to download." I have checked that the path is correct. I can't seem to get the raw dataset...

**Comment by tjqansthd** [comment]
Hi, 

Sorry for the slight mistakes in indicating the directory at README.md.
The above command should be executed in KITTI dataset directory, so I modified README.md from
```bash
    $ cd ./datasets/KITTI
    $ aria2c -x 16 -i ./datasets/kitti_archives_to_download.txt
    $ parallel unzip ::: *.zip
```
to
```bash
    $ mv ./datasets/kitti_archives_to_download.txt ./datasets/KITTI
    $ cd ./datasets/KITTI
    $ aria2c -x 16 -i ./kitti_archives_to_download.txt
    $ parallel unzip ::: *.zip
```
Then the text file will be located in your_workspace/LapDepth-release/datasets/KITTI/kitti_archives_to_download.txt and you can run command " aria2c -x 16 -i ./kitti_archives_to_download.txt" in "your_workspace/LapDepth-release/datasets/KITTI".

**Comment by deng29** [comment]
Hi,


Firstly, thanks very much for your response. But I seem to still have some problems. when I run "aria2c -x 16 -i ./kitti_archives_to_download.txt", its appear error such as follow



"[DL:0B][#a859ed 0B/0B][#ccb996 0B/0B][#230709 0B/0B]&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
05/22 15:53:17 [ERROR] CUID#70 - Download aborted. URI=https://s3.eu-central-1.amazonaws.com/avg-kitti/raw_data/2011_10_03_drive_0034/2011_10_03_drive_0034_sync.zip
Exception: [AbstractCommand.cc:340] errorCode=2 超时。"


I still can't download the raw kitti datasets.&nbsp; I don't know how to do deal with it. whether I need to download one by one .zip files in 'kitti_archives_to_download.txt'?


kind regards.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tjqansthd/LapDepth-release"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月22日(星期六) 凌晨2:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tjqansthd/LapDepth-release] No files to download. (#5)





 
Hi,
 
Sorry for the slight mistakes in indicating the directory at README.md.
 The above command should be executed in KITTI dataset directory, so I modified README.md from
     $ cd ./datasets/KITTI     $ aria2c -x 16 -i ./datasets/kitti_archives_to_download.txt     $ parallel unzip ::: *.zip
 
to
     $ mv ./datasets/kitti_archives_to_download.txt ./datasets/KITTI     $ cd ./datasets/KITTI     $ aria2c -x 16 -i ./kitti_archives_to_download.txt     $ parallel unzip ::: *.zip
 
Then the text file will be located in your_workspace/LapDepth-release/datasets/KITTI/kitti_archives_to_download.txt and you can run command " aria2c -x 16 -i ./kitti_archives_to_download.txt" in "your_workspace/LapDepth-release/datasets/KITTI".

**Comment by tjqansthd** [comment]
I think the server connection in your environment has a slight problem. When I tried to directly click the URI(https://s3.eu-central-1.amazonaws.com/avg-kitti/raw_data/2011_10_03_drive_0034/2011_10_03_drive_0034_sync.zip), it seems that the download proceeded normally in my environment.  So you can try that way(directly access to the URL in  kitti_archives_to_download.txt). 
If you also have a problem with these methods, You can download it directly from the actual official site (http://www.cvlibs.net/datasets/kitti/raw_data.php) by referring to the scene name of the text file( kitti_archives_to_download.txt).
