### ISSUE TITLE
I'd like to konw the difference between gt and dense gt.

### ISSUE THREAD

**Issue by raozhongyu** [tjqansthd/LapDepth-release#6]
Thanks for your great work. I'd like to konw the difference between gt and dense gt. I get the data by carla simulator， so I get the gt with float32. Can I set the same ground truth with gt and dense gt?

**Comment by tjqansthd** [comment]
Hi, thanks for your interest!

Since the KITTI ground truth is very sparse, we get the dense gt depth following [DenseDepth](https://github.com/ialhashim/DenseDepth) to calculate the gradient of the depth map.
If your gt is already dense, you can calculate the gradient loss directly from that gt.

**Comment by raozhongyu** [comment]
I get it. Thanks a lot.
