### ISSUE TITLE
NYU sync train

### ISSUE THREAD

**Issue by jrodriguezpuigvert** [tjqansthd/LapDepth-release#7]
Hi I have a question related to the NYU dataset that you used for training. it contains 36253 sync frames, I was expecting 407,024 frames. 

Is there any reason for that?

**Comment by tjqansthd** [comment]
Hi, after synchronizing raw NYU data, we sampled with a certain step to build a training dataset. This is because the size of the raw dataset is too large and using the whole frame is highly redundant.
